
$('.js-game-1').on('click',function(){
  showModal('いつ？誰と？何する？！ゲーム！','<div class="js-code"><div class="js-code-1"><p class="codepen" data-height="318" data-theme-id="0" data-default-tab="js,result" data-user="szaizen" data-slug-hash="PgWbgE" style="height: 318px; box-sizing: border-box; display: flex; align-items: center; justify-content: center; border: 2px solid black; margin: 1em 0; padding: 1em;" data-pen-title="When?Who?What?GAME!!"><span>See the Pen <a href="https://codepen.io/szaizen/pen/PgWbgE/">When?Who?What?GAME!!</a> by szaizen (<a href="https://codepen.io/szaizen">@szaizen</a>)on <a href="https://codepen.io">CodePen</a>.</span></p><script async src="https://static.codepen.io/assets/embed/ei.js"></script></div></div>');
});
$('.js-game-2').on('click',function(){
  showModal('おみくじ','<p class="codepen" data-height="265" data-theme-id="0" data-default-tab="css,result" data-user="szaizen" data-slug-hash="wZPXpR" style="height: 318px; box-sizing: border-box; display: flex; align-items: center; justify-content: center; border: 2px solid black; margin: 1em 0; padding: 1em;" data-pen-title="wZPXpR">  <span>See the Pen <a href="https://codepen.io/szaizen/pen/wZPXpR/">  wZPXpR</a> by szaizen (<a href="https://codepen.io/szaizen">@szaizen</a>)  on <a href="https://codepen.io">CodePen</a>.</span></p><script async src="https://static.codepen.io/assets/embed/ei.js"></script>');
});
$('.js-game-3').on('click',function(){
  showModal('NumerOn','<p class="codepen" data-height="265" data-theme-id="0" data-default-tab="js,result" data-user="szaizen" data-slug-hash="gyXKKd" style="height: 318px; box-sizing: border-box; display: flex; align-items: center; justify-content: center; border: 2px solid black; margin: 1em 0; padding: 1em;" data-pen-title="NumerOn">  <span>See the Pen <a href="https://codepen.io/szaizen/pen/gyXKKd/">  NumerOn</a> by szaizen (<a href="https://codepen.io/szaizen">@szaizen</a>)  on <a href="https://codepen.io">CodePen</a>.</span></p><script async src="https://static.codepen.io/assets/embed/ei.js"></script>');
});
